version: '3.8'

services:
  gerenciamento:
    build: ./gerenciamento
    container_name: gerenciamento_service
    
    ports:
      - "5000:5000"
    volumes:
      - gerenciamento_data:/app/
    networks:
      - microservice_net
    environment:
      - FLASK_ENV=production

  reservas:
    build: ./reservas
    container_name: reservas_service
  
    ports:
      - "5001:5000"
    volumes:
      - reservas_data:/app/
    networks:
      - microservice_net
  
    depends_on:
      - gerenciamento
    environment:
      - FLASK_ENV=production

  atividades:
    build: ./atividades
    container_name: atividades_service
    
    ports:
      - "5002:5000"
    volumes:
      - atividades_data:/app/
    networks:
      - microservice_net
    depends_on:
      - gerenciamento
    environment:
      - FLASK_ENV=production

networks:
  microservice_net:
    driver: bridge

volumes:
  gerenciamento_data:
  reservas_data:
  atividades_data: